apiVersion: kaptain.org/1.30
kind: kubernetes-bundle-resources
metadata:
  description: "Keelson Argo Rollouts RBAC - optional add-on granting Keelson access to rollouts.argoproj.io, cluster-wide or one namespace at a time"

spec:
  layers:
    - ghcr.io/kube-kaptain/layerset/layerset-cluster-use-project:[1.1]
  global:
    release:
      versioning:
        maxParts: '2'
