# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Keelson contributors (Fred Cooke)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${ProjectName}-role-checksum
  namespace: ${Environment}
  labels:
    kaptain.org/environment: ${Environment}
    kaptain.org/product: ${ProductName}
    kaptain.org/project-name: ${ProjectName}
    kaptain.org/version: "${Version}"
    kaptain.org/owner: ${RepositoryOwner}
    app.kubernetes.io/name: ${ProjectName}
    app.kubernetes.io/instance: ${ProjectName}
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    app: ${ProjectName}
    app.kubernetes.io/part-of: ${ProductName}
  annotations:
    kaptain.org/source-repository: ${RepositoryOwner}/${RepositoryName}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list", "watch", "patch", "update"]
